### ISSUE TITLE
Error Meldungen

### ISSUE THREAD

**Issue by FredF63** [basti4557/ioBroker.komoot#1]
Liegt es daran?
Admin 6.2.4
node 16.16.0
npm 8.11.0
```
2022-07-24 13:30:41.221 - info: host.iobrokertest instance system.adapter.komoot.0 started with pid 49852
2022-07-24 13:30:42.315 - debug: komoot.0 (49852) Redis Objects: Use Redis connection: 0.0.0.0:9001
2022-07-24 13:30:42.374 - debug: komoot.0 (49852) Objects client ready ... initialize now
2022-07-24 13:30:42.385 - debug: komoot.0 (49852) Objects create System PubSub Client
2022-07-24 13:30:42.386 - debug: komoot.0 (49852) Objects create User PubSub Client
2022-07-24 13:30:42.415 - debug: komoot.0 (49852) Objects client initialize lua scripts
2022-07-24 13:30:42.424 - debug: komoot.0 (49852) Objects connected to redis: 0.0.0.0:9001
2022-07-24 13:30:42.442 - debug: komoot.0 (49852) Redis States: Use Redis connection: 0.0.0.0:9000
2022-07-24 13:30:42.450 - debug: komoot.0 (49852) States create System PubSub Client
2022-07-24 13:30:42.451 - debug: komoot.0 (49852) States create User PubSub Client
2022-07-24 13:30:42.461 - debug: komoot.0 (49852) States connected to redis: 0.0.0.0:9000
2022-07-24 13:30:42.676 - info: komoot.0 (49852) starting. Version 0.3.4 (non-npm: basti4557/ioBroker.komoot#7116063b33d915de77484d446e6fdf82b5a3b07f) in /opt/iobroker/node_modules/iobroker.komoot, node: v16.16.0, js-controller: 4.0.23
2022-07-24 13:30:42.720 - debug: komoot.0 (49852) Cookie is valid. Skipping authorisation.
2022-07-24 13:30:44.735 - debug: komoot.0 (49852) {"hostname":"www.komoot.de","port":443,"path":"/discover","method":"GET","headers":{"Host":"www.komoot.de","Content-Type":"application/json","User-Agent":"ioBroker.komoot","Cookie":"*** HIDDEN FOR SECURITY REASONS ***"}}
2022-07-24 13:30:46.405 - error: komoot.0 (49852) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-07-24 13:30:46.405 - error: komoot.0 (49852) unhandled promise rejection: Cannot read properties of null (reading 'getAttribute')
2022-07-24 13:30:46.406 - error: komoot.0 (49852) TypeError: Cannot read properties of null (reading 'getAttribute')
at Object.getUserId (/opt/iobroker/node_modules/iobroker.komoot/lib/komoot-api.js:153:100)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async startKomootApi (/opt/iobroker/node_modules/iobroker.komoot/main.js:70:18)
at async main (/opt/iobroker/node_modules/iobroker.komoot/main.js:62:5)
2022-07-24 13:30:46.406 - error: komoot.0 (49852) Cannot read properties of null (reading 'getAttribute')
2022-07-24 13:30:46.918 - info: komoot.0 (49852) terminating
2022-07-24 13:30:46.920 - warn: komoot.0 (49852) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-07-24 13:30:47.449 - error: host.iobrokertest instance system.adapter.komoot.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-07-24 13:30:47.449 - info: host.iobrokertest Restart adapter system.adapter.komoot.0 because enabled
```

**Comment by basti4557** [comment]
Version 0.3.5 should fix your problem i think :)

**Comment by FredF63** [comment]
> Version 0.3.5 should fix your problem i think :)

Yes it does fix it. Thank you for your fast reply
